version: '3'

services:
   db:
     image: mariadb:10.2
     container_name: ${P_DOMAIN}-db
     hostname: ${P_DOMAIN}-db
     restart: always
     ports:
       - "${P_PORT_1}:3306"
       - "${P_PORT_2}:22"
     volumes:
        - /var/docker-data/container/${P_DOMAIN}/mariadb/mysql:/var/lib/mysql
        - /var/docker-data/container/${P_DOMAIN}/mariadb/backup:/var/backups
     environment:
       MYSQL_ROOT_PASSWORD: ${P_PASSWORD}
       MYSQL_DATABASE: magento2
       PRIMEHOST_USER: ${P_USER}
       PRIMEHOST_PASSWORD: ${P_PASSWORD}
       TZ: "Europe/Berlin"

   magento2:
     depends_on:
       - db
     image: test-magento-php7.1
     #image: primehost/magento2-nginx:php7.1
     container_name: ${P_DOMAIN}-magento2
     hostname: ${P_DOMAIN}
     restart: always
     ports:
       - "80"
       - "${P_PORT_3}:22"
     volumes:
       - /var/docker-data/container/${P_DOMAIN}/nginx/home:/home/
       - /var/docker-data/container/${P_DOMAIN}/nginx/www:/usr/share/nginx/www/
     environment:
       PRIMEHOST_USER: ${P_USER}
       PRIMEHOST_PASSWORD: ${P_PASSWORD}
       PRIMEHOST_DOMAIN: ${P_DOMAIN}
       VIRTUAL_HOST: ${P_DOMAIN}${P_EXTRA_DOMAINS}
       LETSENCRYPT_HOST: ${P_DOMAIN}${P_EXTRA_DOMAINS}
       LETSENCRYPT_EMAIL: ${P_MAIL}
       TZ: "Europe/Berlin"

networks:
    default:
       external:
         name: webproxy
